### ISSUE TITLE
not working with pyramid pserve as expected

### ISSUE THREAD

**Issue by slobinger** [mardiros/plaster-yaml#1]
Tanks for your investment in making an alternative for the ini format pyramid uses by default - I us yout code as orientation to have a bette runderstanding of what to implement to create my own Loader for plaster.

Would be very thankful if you can share any idea about what is going wrong here.

## Whats the problem

If I use plaster-yaml to use a yaml file instead of the PasteDeploy ini file I get the following error:

```
Traceback (most recent call last):
  File "venv/bin/pserve", line 8, in <module>
    sys.exit(main())
  File "/home/lobi/workspace/pyramid_scaffold/venv/lib/python3.8/site-packages/pyramid/scripts/pserve.py", line 30, in main
    return command.run()
  File "/home/lobi/workspace/pyramid_scaffold/venv/lib/python3.8/site-packages/pyramid/scripts/pserve.py", line 196, in run
    self.pserve_file_config(loader, global_conf=config_vars)
  File "/home/lobi/workspace/pyramid_scaffold/venv/lib/python3.8/site-packages/pyramid/scripts/pserve.py", line 152, in pserve_file_config
    settings = loader.get_settings('pserve', global_conf)
  File "/home/lobi/workspace/pyramid_scaffold/venv/lib/python3.8/site-packages/plaster_yaml/loader.py", line 73, in get_settings
    settings = self._conf[section].copy()
KeyError: 'pserve'
```

## Steps to reproduce

1. `$VENV/bin/cookiecutter gh:Pylons/pyramid-cookiecutter-starter --checkout 2.0-branch`
2. cd in new project dir
3. create new venv in project dir (I use venv as dir name)
4. convert the development.ini to development.yaml (see development.yaml below)
5. adjust setup.py (see setup.py below)
6. `venv/bin/pip install -e .[testing]`
7. `venv/bin/pserve development.yaml`

development.yaml
```yaml
'app:main':
  use: 'egg:pyramid_scaffold'
  pyramid.reload_templates: true
  pyramid.debug_authorization: false
  pyramid.debug_notfound: false
  pyramid.debug_routematch: false
  pyramid.default_locale_name: en
  pyramid.includes: ''
  pyramid_debugtoolbar: true
'server:main':
  use: 'egg:waitress'
  listen: 'localhost:6543'
loggers:
  keys: 'root, pyramid_scaffold'
handlers:
  keys: console
formatters:
  keys: generic
logger_root:
  level: INFO
  handlers: console
logger_pyramid_scaffold:
  level: DEBUG
  handlers: ''
  qualname: pyramid_scaffold
handler_console:
  class: StreamHandler
  args: '(sys.stderr,)'
  level: NOTSET
  formatter: generic
formatter_generic:
  format: >-
    %(asctime)s %(levelname)-5.5s [%(name)s:%(lineno)s][%(threadName)s]
    %(message)s
```

setup.py
```python
import os

from setuptools import setup, find_packages

here = os.path.abspath(os.path.dirname(__file__))
with open(os.path.join(here, 'README.txt')) as f:
    README = f.read()
with open(os.path.join(here, 'CHANGES.txt')) as f:
    CHANGES = f.read()

requires = [
    'plaster_pastedeploy',
    'pyramid',
    'pyramid_jinja2',
    'pyramid_debugtoolbar',
    'waitress',
]

tests_require = [
    'WebTest',
    'pytest',
    'pytest-cov',
]

setup(
    name='pyramid_scaffold',
    version='0.0',
    description='Pyramid Scaffold',
    long_description=README + '\n\n' + CHANGES,
    classifiers=[
        'Programming Language :: Python',
        'Framework :: Pyramid',
        'Topic :: Internet :: WWW/HTTP',
        'Topic :: Internet :: WWW/HTTP :: WSGI :: Application',
    ],
    author='',
    author_email='',
    url='',
    keywords='web pyramid pylons',
    packages=find_packages(exclude=['tests']),
    include_package_data=True,
    zip_safe=False,
    extras_require={
        'testing': tests_require,
    },
    install_requires=requires,
    entry_points={
        'paste.app_factory': [
            'main = pyramid_scaffold:main',
        ],
        'plaster.loader_factory': [
            'yaml = plaster_yaml:Loader',
            'file+yaml = plaster_yaml:Loader',
        ],
    },
)
```

**Comment by mardiros** [comment]
Actually, your configuration is wrong. There is no ":main" section in the yaml file,

this is why it does not work. 

You should take a look at the config file in the test:

   https://github.com/mardiros/plaster-yaml/blob/master/tests/config.yaml

For your app, it should be:

```yaml
app:
  use: 'egg:pyramid_scaffold'
  pyramid.reload_templates: true
  pyramid.debug_authorization: false
  pyramid.debug_notfound: false
  pyramid.debug_routematch: false
  pyramid.default_locale_name: en
  pyramid.includes: ''
  pyramid_debugtoolbar: true
server:
  use: 'egg:waitress'
  listen: 'localhost:6543'
loggers:
  keys: 'root, pyramid_scaffold'
handlers:
  keys: console
formatters:
  keys: generic
logger_root:
  level: INFO
  handlers: console
logger_pyramid_scaffold:
  level: DEBUG
  handlers: ''
  qualname: pyramid_scaffold
handler_console:
  class: StreamHandler
  args: '(sys.stderr,)'
  level: NOTSET
  formatter: generic
formatter_generic:
  format: >-
    %(asctime)s %(levelname)-5.5s [%(name)s:%(lineno)s][%(threadName)s]
    %(message)s
```

Fill free to reopen if it does not work.

**Comment by slobinger** [comment]
Tanks. Just for completeness:
I have corrected the development.yaml to look like https://github.com/mardiros/plaster-yaml/blob/master/tests/config.yaml
but the error remains.  Seems that the pserve command searches for a key 'pserve' in the config if it is not paste_deploy.
I have changed my yaml to the following:
```yaml
app:
  use: 'egg:pyramid_scaffold'
  pyramid.reload_templates: true
  pyramid.debug_authorization: false
  pyramid.debug_notfound: false
  pyramid.debug_routematch: false
  pyramid.default_locale_name: en
  pyramid.includes: ''
  pyramid_debugtoolbar: true
server:
  use: 'egg:waitress'
  listen: 'localhost:6543'
pserve:
  use: 'egg:waitress'
  listen: 'localhost:6543'
logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    console:
      format: '%(asctime)s [%(levelname)s]: %(name)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      stream: ext://sys.stdout
      formatter: console
  root:
    level: INFO
    handlers:
      - console
  loggers:
    dummy:
      level: DEBUG
```
This config works. Question was now for me if 'server' key is still needed. So I changed the development.yaml as follow:
```yaml
app:
  use: 'egg:pyramid_scaffold'
  pyramid.reload_templates: true
  pyramid.debug_authorization: false
  pyramid.debug_notfound: false
  pyramid.debug_routematch: false
  pyramid.default_locale_name: en
  pyramid.includes: ''
  pyramid_debugtoolbar: true
# server:
#   use: 'egg:waitress'
#   listen: 'localhost:6543'
pserve:
  use: 'egg:waitress'
  listen: 'localhost:6543'
logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    console:
      format: '%(asctime)s [%(levelname)s]: %(name)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      stream: ext://sys.stdout
      formatter: console
  root:
    level: INFO
    handlers:
      - console
  loggers:
    dummy:
      level: DEBUG
```
`pserve development.yaml` gives following error. 
```
Traceback (most recent call last):
  File "venv/bin/pserve", line 8, in <module>
    sys.exit(main())
  File "/home/lobi/workspace/pyramid_scaffold/venv/lib/python3.8/site-packages/pyramid/scripts/pserve.py", line 30, in main
    return command.run()
  File "/home/lobi/workspace/pyramid_scaffold/venv/lib/python3.8/site-packages/pyramid/scripts/pserve.py", line 269, in run
    server = server_loader.get_wsgi_server(server_name, config_vars)
  File "/home/lobi/workspace/pyramid_scaffold/venv/lib/python3.8/site-packages/plaster_yaml/loader.py", line 88, in get_wsgi_server
    settings = self.get_settings("server", defaults)
  File "/home/lobi/workspace/pyramid_scaffold/venv/lib/python3.8/site-packages/plaster_yaml/loader.py", line 73, in get_settings
    settings = self._conf[section].copy()
KeyError: 'server'
```
Looks like server key is still required. Same for the sub entry `use`.
But the pserve dict can be empty:
```yaml
app:
  use: 'egg:pyramid_scaffold'
  pyramid.reload_templates: true
  pyramid.debug_authorization: false
  pyramid.debug_notfound: false
  pyramid.debug_routematch: false
  pyramid.default_locale_name: en
  pyramid.includes: ''
  pyramid_debugtoolbar: true
server:
  use: 'egg:waitress'
#   listen: 'localhost:6543'
pserve: {}
  # use: 'egg:waitress'
  # listen: 'localhost:6543'
logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    console:
      format: '%(asctime)s [%(levelname)s]: %(name)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      stream: ext://sys.stdout
      formatter: console
  root:
    level: INFO
    handlers:
      - console
  loggers:
    dummy:
      level: DEBUG
```
This one works.
I would suggest to set an empty dict as default for `pserve` - seems that `pserve` command strictly requires it.
